name: hspl2shop

services:
  postgres:
    image: 'postgres:latest'
    restart: on-failure
    environment:
      - 'POSTGRES_DB=hspl2shop'
      - 'POSTGRES_PASSWORD=123'
      - 'POSTGRES_USER=hspl'
    ports:
      - '5432:5432'
