name: hspl2shop

services:
  postgres:
    image: 'postgres:18'
    restart: on-failure
    environment:
      - 'POSTGRES_DB=hspl2shop'
      - 'POSTGRES_PASSWORD=123'
      - 'POSTGRES_USER=hspl'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: